### ISSUE TITLE
Allow sampling texture from sprite sheet

### ISSUE THREAD

**Issue by vultix** [djeedai/bevy_hanabi#108]
It's common for particles to be animated using a spritesheet, allowing you to create effects like in [this video](https://www.youtube.com/watch?v=u7hRDl2yQmM).

I'm planning on working on this during the next week or two, so any feedback would be appreciated.

## Current Plan
I'm going  to update the `RenderLayout` struct to look like this:

```rust
#[derive(Debug, Default, Clone, PartialEq)]
pub struct RenderLayout {
    pub particle_texture: Option<ParticleTexture>,
    ...
}

pub enum ParticleTexture {
    Image(Handle<Image>),
    TextureAtlas {
        texture: Handle<TextureAtlas>,
        /// The index of the texture in the texture atlas.
        lifetime_texture_index_gradient: Gradient<f32>,
        /// How to interpolate between two textures in the texture atlas.
        texture_interpolation: TextureInterpolation,
    }
}

pub enum TextureInterpolation {
    Nearest,
    LinearBlend
}
```

In addition to the `PARTICLE_TEXTURE` shader key, I'll add a new `PARTICLE_TEXTURE_ATLAS` shader key, which will enable sampling a subset of the uvs following the configuration in the `ParticleTexture` enum.

**Comment by vultix** [comment]
I'm still not sure how best to represent all of this as modifiers.  Here's a few questions:

1. Should the `ParticleTextureModifier` be updated to use an enum like the `ParticleTexture` enum above, or should I create a new `ParticleTextureAtlasModifier`?
    - If we keep these as separate modifiers, how do we handle the mutually exclusive modifiers? Do we just panic at runtime? 	
2. Should the `lifetime_texture_index_gradient` be its own modifier, or a required part of the texture atlas modifier?
    - Should this be a required modifier? We could default to only showing the first sprite in the texture atlas.
3. Same question as above, just relating to the texture interpolation

I'm currently leaning towards keeping the single `ParticleTextureModifier`, and updating its field to be of the above enum type `ParticleTexture`.  This seems to be simplest from both an implementation and a user-facing perspective.  I also don't think we should split the `lifetime_texture_index_gradient` and `texture_interpolation` fields into their own modifiers, as I don't imagine you'll ever want to use a TextureAtlas without specifying those.

**Comment by djeedai** [comment]
@vultix thanks for the issue. I agree the use case is valid and should be supported.

I'd note that I'm currently working on #109 to make the particle layout dynamic, and as part of this change there's a very high chance that `InitLayout` / `UpdateLayout` / `RenderLayout` disappear; they were never meant to be long-term solutions.

That being said, I think there's a bit of design discussion to be having ahead of any change, as you pointed there's a few questions to answer and I don't have those answers yet. And the `ParticleTextureModifier` itself is unlikely to go anywhere, so any prototype change you'd try wouldn't be wasted.

Eventually I think the current `ParticleTextureModifier` does too many things already to make it really versatile. I think I'd like to move toward something like Unity's VFX graph, with more basic operators like "sample a 2D texture" and "assign the color value", and by combining those you'd be able to recreate your own equivalent of either the current `ParticleTextureModifier` or the variant for sprite sheets you propose, without any library change. But that feature might be a bit further down the road, so I'm open to consider a simple/minimal change in the meantime to support sprite sheets.

**Comment by vultix** [comment]
Gotcha.  I think I'll wait until you finish #109 before working on this then, as that sounds quite useful.  I'll be in touch

**Comment by auderer** [comment]
@vultix , #109 is merged now, in case you're still interested in picking this up. I think having a simple texture atlas API would be really nice for a ton of use cases

**Comment by djeedai** [comment]
#246 adds flipbook animtion from a spritesheet defined as a texture sliced by a regular grid. The rationale for _not_  using `TextureAtlas` is that I had a look at it and it has 2 issues:
- it defines generic sprites of all sizes, while we need a fixed-size sprite for animation.
- it defines an arbitrary per-sprite location inside the texture, which would require uploading to GPU all rectangles of all sprites so the texture can sample the right sprite data.

So as a simplified model, the `FlipbookModifier` simply takes a grid size and uniformly slices the input texture to generate animation sprites. This is a lot more predictable and easy to handle on GPU (and therefore faster, although maybe marginally, I didn't test).
