### ISSUE TITLE
Generalize vertex_modifiers?

### ISSUE THREAD

**Issue by brandon-reinhart** [djeedai/bevy_hanabi#120]
Unlike some of the other customizable shader code blocks, it looks like vertex_modifiers isn't fully configurable. It might be preferable to make this block more configurable, to enable things like per-vertex color randomization or drawing from noise.

**Comment by djeedai** [comment]
Are you really talking about vertex (which is not really useful until mesh particles are supported, is it?) or about particle attributes? Is that a duplicate of #109 maybe?

**Comment by brandon-reinhart** [comment]
My goal is to be able to write the vertex color. Didn't seem I could do that currently. I'll look at #109

**Comment by brandon-reinhart** [comment]
Yes #109 dupe
