### ISSUE TITLE
Hanabi 0.5.2 Causes Panic on Unwrap

### ISSUE THREAD

**Issue by Braymatter** [djeedai/bevy_hanabi#123]
I've got an app that is spawning/despawning several particle emitters as part of an asteroid mining thing. New particle systems work better, in that systems spawned after another has been despawned now work; however there seems to be a crash caused by pulling an unwrap()

 thread 'Compute Task Pool (2)' panicked at 'assertion failed: (left == right)
  left: 11,
 right: 0: Broken table invariant: buffer=0 row=11', /Users/nope/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_hanabi-0.5.2/src/render/mod.rs:1375:13
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread 'main' panicked at 'called Option::unwrap() on a None value', /Users/nope/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.9.1/src/task_pool.rs:273:45

Dep: 
bevy_hanabi = { version = "0.5.2", default-features = false, features = [ "2d" ] }

**Comment by djeedai** [comment]
Sorry about that. Do you have a repro handy @Braymatter, maybe based on one of the examples? Or can you describe some sequence of events that lead to this? I ran all examples manually and did some tests before the release, and I couldn't hit that case, so I'm not sure how to debug.

**Comment by djeedai** [comment]
Ok I have a minimal repro, investigating...

**Comment by djeedai** [comment]
Ok I  think I have a fix, this stress test has been running for several minutes randomly spawning and despawning (and clearing all sometimes), and no crash.

![instacing_stress_test](https://user-images.githubusercontent.com/6532395/213928346-dbdaf172-7ce9-4765-8ffc-831ad9edd31c.gif)

**Comment by Braymatter** [comment]
I'll point my app at master and test on my end when it gets merged in; thanks for the speedy fix!

**Comment by djeedai** [comment]
Merged. Please reopen @Braymatter if there's still an issue. I wrote a stress test (see above) and had no crash, though I admit I think I've seen a rendering bug. But I've hit that once only, and not even sure it was really a bug or just the stress test doing weird things, so that will be for another debug session another day.

**Comment by Braymatter** [comment]
This is fixed for me! Thank you very much for fixing it so quickly!
