### ISSUE TITLE
PositionCone3dModifier generates particles at wrong location 

### ISSUE THREAD

**Issue by OleStrohm** [djeedai/bevy_hanabi#152]
When using the PositionCone3d the particles are generated at a location that seems to be 2x (in each dimension) the actual translation of the entity.

When going back to the InitPositionCircleModifier the particles are generated around the correct center.

Version: main (specifically 8cbfa36080)

**Comment by djeedai** [comment]
Just released v0.6.1 with that fix and a new example `init.rs` to show the various position initializers. Also switched the `spawn.rs` example to use the newly-renamed `InitPositionCone3dModifier`, for better coverage.
