### ISSUE TITLE
disable the spawner or remove it without removing the spawned particles

### ISSUE THREAD

**Issue by KnstAnt** [djeedai/bevy_hanabi#155]
Hello. I want to make a trail effect during the flight of a projectile or rocket. After the projectile hits, in order to stop the spawning of particles, I remove the emitter, while the particles caused by it disappear. This looks bad, it would be better to let the particles go by themselves. How can I do that?

**Comment by djeedai** [comment]
See the https://github.com/djeedai/bevy_hanabi/blob/main/examples/activate.rs example. You need to deactivate the spawner to stop emitting. Then wait enough for all particles to die (based on how you configured their lifetime) and only after that you can if you want remove the component.

**Comment by KnstAnt** [comment]
Yes, it looks like what I need. Thank you.
