### ISSUE TITLE
Spawning effects with different textures causes problems

### ISSUE THREAD

**Issue by NiseVoid** [djeedai/bevy_hanabi#167]
**Crate versions**
`bevy` version: 0.10
`bevy_hanabi` version: both 0.6.1 and current main

**Describe the bug**
When creating an effect with a different texture than the previous one, the texture of the previous effect changes to the texture of the new effect.

**Expected behavior**
The texture matching what was configured by the effect

**To Reproduce**
I could reproduce this bug anytime I spawned effects with different textures.
An easy way to figure out what exactly is going on was changing the instancing example by making it pick from a list of effects, each with a unique combination of texture and color.

**Screenshots**
In this screenshot I configured three effects: blue squares, red circles and green triangles. But you can also see effects where the color and shape don't match, on each of these the texture changed when the next effect was spawned.
![image](https://user-images.githubusercontent.com/3254486/227745817-d686af11-45cf-4024-ab51-d7f1cee220dc.png)

**Comment by djeedai** [comment]
Thanks @NiseVoid I will have a look. Do you have your modified example at hand please, so I don't waste time trying to rewrite it?

**Comment by NiseVoid** [comment]
This is the code and the assets I used
[texture-swap-repro.zip](https://github.com/djeedai/bevy_hanabi/files/11072764/texture-swap-repro.zip)

**Comment by djeedai** [comment]
Thanks I will have a look

**Comment by djeedai** [comment]
Confirmed repro, thanks

**Comment by djeedai** [comment]
Should be fixed on `main`, that was just a silly batching bug.
