### ISSUE TITLE
Soooo... you don't support Linux????

### ISSUE THREAD

**Issue by HyperAlch** [djeedai/bevy_hanabi#170]
**Crate versions**
`bevy` version: _e.g. 0.10_
`bevy_hanabi` version: _e.g. 0.6.1_

**Describe the bug**
When compiling any example: `error: The platform you're compiling for is not supported by winit`

**Expected behavior**
Compile....

**To Reproduce**
I guess try to compile on any Ubuntu based distro?

**Screenshots**
![image](https://user-images.githubusercontent.com/43654357/228097054-148bff95-8e9a-4410-b0c8-29d42951f851.png)

**Comment by djeedai** [comment]
CI build on Ubuntu 22.04

**Comment by HyperAlch** [comment]
I mean, that's cool and all, but my Bevy game compiles with no issue and it to relies on `winit`

So the ball is kind in your court

**Comment by HyperAlch** [comment]
PS: If you don't have a Linux install I would be happy to help you test any changes you make to the `Config.toml` in order to fix the issue.

Also, let me know if you need more information

**Comment by djeedai** [comment]
How did you compile the examples?

**Comment by HyperAlch** [comment]
Like it's shown on the `README.md` and `run_examples.sh`

For Example:
```bash
cargo r --example portal --no-default-features --features="bevy/bevy_winit bevy/bevy_pbr 3d"
```
And
```bash
cargo run --example portal --features="bevy/bevy_winit bevy/bevy_pbr bevy/png 3d"
```

I've also tried other examples other than `portal`
