### ISSUE TITLE
Spawning effects with and without textures causes problems

### ISSUE THREAD

**Issue by NiseVoid** [djeedai/bevy_hanabi#181]
**Crate versions**
`bevy` version: 0.10.1
`bevy_hanabi` version: current main

**Describe the bug**
Like issue https://github.com/djeedai/bevy_hanabi/issues/167, but using an effect without textures.

**Expected behavior**
Particles using the textures that were specified

**To Reproduce**
Similar repro to https://github.com/djeedai/bevy_hanabi/issues/167 but one of the effects needs to have no ParticleTextureModifier

**Comment by djeedai** [comment]
I believe this was fixed as part of #194. I tested on one example and I was able to spawn both textured and non-textured effects at the same time.
