### ISSUE TITLE
Canvas takes color of bevy_smud shape when there is bevy_hanabi particles effect in the same position

### ISSUE THREAD

**Issue by StaffEngineer** [djeedai/bevy_hanabi#188]
**Crates versions**
`bevy` version: _0.10_
`bevy_hanabi` version: _0.6_
`bevy_smud` version: _0.5_

**Describe the bug**
Black screen when particles effect start point is the same as `bevy_smud` shape. Do you see any reason this may happen? Any help would be appreciated.

**Expected behavior**
`bevy_smud` and `bevy_hanabi` works nicely together all the time. 

**To Reproduce**
Code that spawns particles: https://github.com/StaffEngineer/velo/blob/c4a0b412f6df6a98819a4f20b59d12f453c24e15/src/ui_plugin/systems/button_handlers.rs#L601
Code that spawns bevy_smud shape:
```rs
        let fill = shaders.add_fill_body(format!(
            "
        let size = {:.2};
        let power = 10.0;
        var a = (size - d) / size;
        a = clamp(a, 0.0, 1.0);
        a = pow(a, power);
        return vec4<f32>(color.rgb, a * color.a);
    ",
            width
        ));
        let sdf_expr = format!(
            "sd_box(p, vec2<f32>({:.2}, {:.2}))",
            0.7 * (width / 2.),
            0.7 * (height / 2.),
        );
        let sdf = shaders.add_sdf_expr(sdf_expr);
        let translation = Vec3::new(-0.025 * width, -0.10 * height, 0.09);

        let shadow = commands
            .spawn(ShapeBundle {
                transform: Transform {
                    translation,
                    ..default()
                },
                shape: bevy_smud::SmudShape {
                    color: Color::BLACK,
                    sdf,
                    fill,
                    frame: Frame::Quad(width),
                    ..default()
                },
                ..default()
            })
            .id();
```

**Note**
If  `Color::BLACK` changed to `Color::RED` for bevy_smud entity then the canvas becomes red.

**Video**

https://github.com/djeedai/bevy_hanabi/assets/111751109/c2f4b7e8-06d7-47ab-921b-753d2d4c44b8

**Comment by djeedai** [comment]
I don't know what `bevy_smud` is. Wildest guess is some bad interaction with the camera settings. I would have said maybe some particle getting infinitely big, but since the canvas color is different from the particle one that's probably not it. Best debugging in RenderDoc see what's actually rendering that full screen quad.
