### ISSUE TITLE
0.6.1 -> 0.6.2 should have been 0.7.0

### ISSUE THREAD

**Issue by thedodd** [djeedai/bevy_hanabi#195]
**Describe the solution you'd like**
Let's stick with semver a bit more closely. The most recent change from 0.6.1 -> 0.6.2 entirely broke my particle effects. Incompatible code & a change in patterns. Given that this project is in the 0.X phase, this type of change should really have been part of a 0.7 release. 

**Describe _why_ you want that solution. Is this related to a problem?**
We all use software, and this is a well understood issue in any software community these days. Probably not much that needs to be expressed here. It was a surprise to see all of the things related to this project break as part of a "bug fix" / patch release.

**Describe alternatives you've considered**
Stick with semver. In this type of situation, just bump the minor version (`major.minor.version`, eg `0.7.0` instead of `0.6.2`).

**Additional context**
As a maintainer, I totally get this. It probably was not intentional, or the impact was perceived as being quite low. I understand. However, I would argue that bumping the minor version is not a big deal at all. Stability is much more important.

**Comment by thedodd** [comment]
Feel free to close, this is more of a discussion item. I wanted to take the time to highlight this so that I don't have to loose another few hours again in the future when performing what should have been a totally safe update `:)`.

**Comment by djeedai** [comment]
https://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

So yes, this project strictly adheres to SemVer.

**Comment by thedodd** [comment]
@djeedai the issue is a bit deeper than that. Let's talk specifically about Rust real quick. Rust has cargo, everyone uses it, and [this is what cargo does](https://doc.rust-lang.org/cargo/reference/semver.html). Specifically, note the following:

> This guide uses the terms “major” and “minor” assuming this relates to a “1.0.0” release or later. Initial development releases starting with “0.y.z” can treat changes in “y” as a major release, and “z” as a minor release. “0.0.z” releases are always major changes. This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

To be painfully precise, this is cargo's behavior you are fighting against: `This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.`

So, my question is, given that cargo works this way, why not just bump to 0.7? You didn't have to choose 0.6.2 which would break anyone that does `cargo update`. This is an anti-pattern. I would recommend, humbly, just don't do that. 

Once again, I empathize. But this is Rust and cargo. We should, as maintainers, consider the subtle difference in cargo's behavior vs what you might believe semver should be like.

**Comment by SludgePhD** [comment]
Yes, for better or worse, Cargo/crates.io do not use vanilla SemVer. In fact, Cargo is basically completely incompatible with even just a single user-facing crate not adhering to "Cargo SemVer" because of how the version selection algorithm works.
