### ISSUE TITLE
Particles doesn't spawn on Windows [Bootcamp on mac M1]

### ISSUE THREAD

**Issue by ghashy** [djeedai/bevy_hanabi#202]
**Crate versions**
`bevy` version:  0.10.1
`bevy_hanabi` version: 0.6.2

**Describe the bug**
Hello! I've noticed that the particles system doesn't work on Windows. I'm making a [game](https://github.com/ghashy/Space-Kitty) on M1 mac, and the particles work perfectly there and on the other iMac late 2012. On this iMac I have installed Windows with Bootcamp. And I found out that the particles don't spawn there. I've printed lines where I'm calling the functions to spawn the particles, and there are lines in the terminal that the particles should be there. But they don't. Did I do something wrong? Or it's some Windows issue I don't know about?

**Comment by djeedai** [comment]
Hi- It's not a Windows issue, I use Windows and everything works fine. I suspect there's a weird thing going on with shaders and Bootcamp, but I have no way to debug that unfortunately.

**Comment by djeedai** [comment]
There's a good chance this is fixed @ghashy, if you have a chance to try again on latest `main`?

**Comment by ghashy** [comment]
Thanks, I will try in some time!

**Comment by djeedai** [comment]
I'll close for now, as things generally work on mac silicon. Feel free to reopen if there's still an issue. Thanks
