### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by paholg** [djeedai/bevy_hanabi#213]
**Crate versions**
`bevy` version: 0.11
`bevy_hanabi` version: 0.7

**Describe the bug**
The code in the readme uses out-of-date code which no longer compiles in 0.7. For example,

```rust
  .init(SetVelocitySphereModifier {
      center: Vec3::ZERO,
      speed: 6.0.into(),
  })
```

---

As a long-term solution, I can recommend placing the following line in lib.rs:

```
#![doc = include_str!("../README.md")]
```

This will allow your README.md to serve as the front-page of the API docs, and will ensure that the code in it is tested. Though, your readme and lib docs differ enough that you may not wish to do this.

**Comment by djeedai** [comment]
Thanks, I generally pay attention to that but this one slipped through the cracks.

> As a long-term solution, I can recommend placing the following line in lib.rs:

Thanks for the suggestion. I do like the approach which avoids duplication, and ensures the code is tested. However as you spotted currently there's quite a bit more information in the README that feel out of place in `lib.rs`, like the list of examples. On one hand, the list has grown past a reasonable size, so I'd like to find an alternative presentation, which could maybe then reconcile README with `lib.rs`. On the other hand, I believe this library is at its core a graphics one so having visuals on the front page of the repository is rather critical to showcase what it can do. So I'm a bit torn here.
