### ISSUE TITLE
billboard can't find a module

### ISSUE THREAD

**Issue by lx2720** [djeedai/bevy_hanabi#230]
![1](https://github.com/djeedai/bevy_hanabi/assets/19430019/f032b32d-58b0-461e-a82f-6605060d0d8e)
hello bro! My bevy version is 0.11.2, and the hanabi version is 0.7. I posted the reference example of the billboard, but there was an error and the OrientModifier could not be found·

**Comment by lx2720** [comment]
![2](https://github.com/djeedai/bevy_hanabi/assets/19430019/f6f67483-8caf-4e2a-b749-9b8c8608dac0)
and this is my cargo.toml

**Comment by djeedai** [comment]
Try again, politely.
