### ISSUE TITLE
Changing number of particles spawned on command

### ISSUE THREAD

**Issue by Hippo** [djeedai/bevy_hanabi#238]
Hi, I'm relatively new to `bevy_hanabi`. I've been trying to figure out how to adjust the number of particles that are spawned on command. While exploring the repository, I discovered that altering the `num_particles` through the `Spawner` within the `EffectSpawner` achieves this. However, given that this is not a part of the public API I assume its undefined behavior? Is there a more official way to do this?

**Comment by djeedai** [comment]
The `Spawner::num_particles` is not part of the public API because it's an internal representation subject to change. But you can override the entire `EffectAsset::spawner` to change all instances, or the `ParticleEffect::spawner` to change a single instance.

**Comment by Hippo** [comment]
Thanks for the reply, found the solution to my issue.
