### ISSUE TITLE
Ability to pause / unpause effects independently from Bevy Time

### ISSUE THREAD

**Issue by wilk10** [djeedai/bevy_hanabi#239]
**Describe the solution you'd like**
I would like to stop the particles in place on demand, when I want. I don't mean spawing / despawning them, I mean just stop them in place wherever they are, and later continue from where they were. 
I am able to achieve this by pausing / unpausing `Res<Time>` provided by Bevy itself, but the problem is that I can't move the camera anymore (and anything else that depends on Bevy's `Time` has to be paused too). So I would like the ability to just pause / unpause effects independently from pausing / unpausing Bevy's `Time`.

**Describe _why_ you want that solution. Is this related to a problem?**
In my builder game when the player wants to add a new building, the game enters a new state where characters movement is paused, particle execution is paused etc. They then place the building where they want and go back to the `Play` state. With the current situation I can either pause the particles execution while the new building is being placed, but also block the camera movement (because it depends on Bevy's `time.delta_seconds()` as well), or pause neither, so the camera can be moved, but the particle effects continue to execute, which looks odd.

**Describe alternatives you've considered**
Perhaps there is already a way to achieve this and I have missed it. Alternatively it can stay as is, but I feel it's a bit limiting.

**Additional context**
I can provide a GIF, if what I described is not clear.

(by the way thanks a lot for the library, it's amazing and I recommend it whenever relevant)

**Comment by jannik4** [comment]
Also answered in the PR, but I think having a `Time<EffectSimulation>` on top of `Time<Virtual>` seems to be the right move.

(Regardless of whether a per component/entity time scale should perhaps additionally be possible, I think a global option is necessary anyway.)
