### ISSUE TITLE
Spawn example crashes on Intel Mac

### ISSUE THREAD

**Issue by malleusinferni** [djeedai/bevy_hanabi#26]
As of commit ca6d4a03ccd8cb50bc6d7851fd7f80362fc24a3d, the `spawn` example panics in the wgpu backend on a 2019 Intel MacBook Pro with Radeon 5500M graphics.

The following error is printed by the panic message:

```
wgpu error: Validation Error

Caused by:
    In a ComputePass
      note: encoder = `<CommandBuffer-(0, 1, Metal)>`
    In a set_bind_group command
      note: bind group = `particles_spawner_bind_group`
    dynamic binding at index 0: offset 576 does not respect device's requested `min_storage_buffer_offset_alignment` limit 256
```

This panic further results in a failed assertion in the Metal layer (because the command encoder is prematurely released) which triggers an Apple crash report dialogue.

I haven't yet had the chance to check how the example behaves on other Apple hardware or OS versions.

**Comment by djeedai** [comment]
Discussed on Discord [here](https://discord.com/channels/691052431525675048/866787577687310356/970233097113178112).

**Comment by djeedai** [comment]
Fixed. Also added some code in the `spawn` example to force aligning to 256 bytes to test that codepath. Other examples are left untouched.
