### ISSUE TITLE
Visibility check is not optimal for 2D 

### ISSUE THREAD

**Issue by zaycev** [djeedai/bevy_hanabi#272]
**Crate versions**
_This is critical, please fill. The code is evolving fast, and many bugs get fixed. If you're not on latest please try first on latest release if you can, chances are the bug is fixed there._
`bevy` version: _e.g. 0.12
`bevy_hanabi` version: `82e0877c511ee4ba515115e1a943f301c22e5969`

**Describe the bug**

Since bevy does not cull any entities from 2D view, visibility check in hanabi is very expensive. In a scene with 1 camera, 100 emitters and 10k entities, it takes ~20ms to run `emit_draw` in debug mode and  1ms in release mode.

**Expected behavior**
Not sure if this is better to fix in Bevy or Hanabi. The solution I had is to add a custom AABB field in `EffectBatch` and do culling inside of hanabi, also not allocating additional vec of visible entities for each view.

**To Reproduce**
Create 10k entities with off-screen coordinates in setup function in 2d example:
```rust
fn setup(
    mut commands: Commands,
    mut effects: ResMut<Assets<EffectAsset>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {

    // Create 10k objects offscreen.
    for i in 0..10_000 {
        commands.spawn(SpatialBundle::from_transform(Transform::from_xyz(-100_000.0, 100_000.0, 0.0)));
    }

    // Spawn a 2D camera
    let mut camera = Camera2dBundle::default();
    camera.projection.scale = 1.0;
    camera.projection.scaling_mode = ScalingMode::FixedVertical(1.);
    commands.spawn(camera);

    // Spawn a reference white square in the center of the screen at Z=0
    commands
        .spawn(MaterialMesh2dBundle {
            mesh: meshes
                .add(Mesh::from(shape::Quad {
                    size: Vec2::splat(0.2),
                    ..Default::default()
                }))
                .into(),
            material: materials.add(ColorMaterial {
                color: Color::WHITE,
                ..Default::default()
            }),
            ..Default::default()
        })
        .insert(Name::new("square"));

    // Create a color gradient for the particles
    let mut gradient = Gradient::new();
    gradient.add_key(0.0, Vec4::new(0.5, 0.5, 1.0, 1.0));
    gradient.add_key(1.0, Vec4::new(0.5, 0.5, 1.0, 0.0));

    let writer = ExprWriter::new();

    let age = writer.lit(0.).expr();
    let init_age = SetAttributeModifier::new(Attribute::AGE, age);

    let lifetime = writer.lit(5.).expr();
    let init_lifetime = SetAttributeModifier::new(Attribute::LIFETIME, lifetime);

    let init_pos = SetPositionCircleModifier {
        center: writer.lit(Vec3::ZERO).expr(),
        axis: writer.lit(Vec3::Z).expr(),
        radius: writer.lit(0.05).expr(),
        dimension: ShapeDimension::Surface,
    };

    let init_vel = SetVelocityCircleModifier {
        center: writer.lit(Vec3::ZERO).expr(),
        axis: writer.lit(Vec3::Z).expr(),
        speed: writer.lit(0.1).expr(),
    };

    // Create a new effect asset spawning 30 particles per second from a circle
    // and slowly fading from blue-ish to transparent over their lifetime.
    // By default the asset spawns the particles at Z=0.
    let spawner = Spawner::rate(30.0.into());
    let effect = effects.add(
        EffectAsset::new(4096, spawner, writer.finish())
            .with_name("2d")
            .init(init_pos)
            .init(init_vel)
            .init(init_age)
            .init(init_lifetime)
            .render(SizeOverLifetimeModifier {
                gradient: Gradient::constant(Vec2::splat(0.02)),
                screen_space_size: false,
            })
            .render(ColorOverLifetimeModifier { gradient }),
    );

    // Spawn an instance of the particle effect, and override its Z layer to
    // be above the reference white square previously spawned.
    for _ in 0..100 {
        commands
            .spawn(ParticleEffectBundle {
                // Assign the Z layer so it appears in the egui inspector and can be modified at runtime
                effect: ParticleEffect::new(effect.clone()).with_z_layer_2d(Some(0.1)),
                ..default()
            })
            .insert(Name::new("effect:2d"));
    }

}
```

**Screenshots**

**Comment by djeedai** [comment]
For reference the sprite renderer does the same, so probably had the same issue:

https://github.com/bevyengine/bevy/blob/f1f83bf5bc898140bff862a7279b5cd318f38661/crates/bevy_sprite/src/render/mod.rs#L509-L521

Weirdly though this issue seems to imply sprites are culled?!

https://github.com/bevyengine/bevy/issues/11081

**Comment by zaycev** [comment]
> For reference the sprite renderer does the same, so probably had the same issue:
> 
> https://github.com/bevyengine/bevy/blob/f1f83bf5bc898140bff862a7279b5cd318f38661/crates/bevy_sprite/src/render/mod.rs#L509-L521
> 
> Weirdly though this issue seems to imply sprites are culled?!
> 
> [bevyengine/bevy#11081](https://github.com/bevyengine/bevy/issues/11081)

I wonder if you can just do exactly what Bevy does in `queue_sprites` to mitigate this - e.g. create and re-use a bitset, instead of re-allocating and copying all entities from view to your vec on each iteration, because I don't really see `queue_sprites` in my project taking any significant time for ~20k sprites, but I see it for hanabi pipeline.

I can try to experiment with it.

**Comment by djeedai** [comment]
Ok I managed to get Tracy to work. Let the 😱 begin...

![image](https://github.com/djeedai/bevy_hanabi/assets/6532395/daee7cf5-da24-472b-9896-c69e7c4d24d4)

(x304) aaaaaaah...!!

**Comment by djeedai** [comment]
@zaycev this should be fixed, visibility check now caches a `FixedBitSet` across frames, preventing any allocation. There's also a bunch of bind group caching optimization. Overall using your example I measured over 1ms saved.
