### ISSUE TITLE
Spawner Enhancements

### ISSUE THREAD

**Issue by josh65536** [djeedai/bevy_hanabi#3]
I'd like for there to be some other things you can do with spawners, such as:
- activating/deactivating them
- resetting (for `SpawnMode::Once`, this would allow bursts to be controlled by game logic)
- disappearing after a certain number of seconds.

I was going to implement them, but I'm not sure if this would interfere with any planned spawner cleanup system.

**Comment by djeedai** [comment]
No, there's no plan to modify the CPU side spawning at the moment, feel free to implement those. I'm working on the internal infrastructure to improve init/update/render on GPU, but that shouldn't change anything for the spawner (only _when_ it runs).
