### ISSUE TITLE
[3D] Particles render through PBR objects with AlphaMode::Blend

### ISSUE THREAD

**Issue by Katsutoshii** [djeedai/bevy_hanabi#320]
**Crate versions**
`bevy` version: 0.13.2
`bevy_hanabi` version: 0.10.0

**Describe the bug**
In 3d scenes, particles render behind PBR objects with AlphaMode::Blend but Color.alpha = 1.0. Note that the particles *do* get occluded when AlphaMode::Opaque.
My use case is spawning particles in a world where I have a fog of war layer between the world and the camera, but the particles render through the fog.

**Expected behavior**
I expect particles to be occluded by objects that are between them and the camera, even if AlphaMode is not AlphaMode::Opaque

**To Reproduce**
I have a minimal reproduction in this repo: https://github.com/Katsutoshii/hanabi_blend.

**Screenshots**
Mp4 attached. The blue and green squares are both closest to the camera and the red square is behind the fireworks. This shows that with AlphaMode::Opaque (green), the particles are correctly occluded, but for AlphaMode::Blend (blue) the particles are not.

https://github.com/djeedai/bevy_hanabi/assets/22205099/c70bba95-9adf-4f4b-8332-0d238e4b1a31

**Comment by djeedai** [comment]
Fixed.
