### ISSUE TITLE
Cannot see more than 64 copies of Ribbon example particle effect

### ISSUE THREAD

**Issue by jakkos-net** [djeedai/bevy_hanabi#321]
**Crate versions**
`bevy` version: 0.13.2
`bevy_hanabi` version: [2da6d8d](https://github.com/djeedai/bevy_hanabi/commit/2da6d8db1a02e028b279b5910eb2f1a75854c67c)

**Describe the bug**

Spawning 100 copies of the particle effect bundle from the Ribbons example leads to only 64 being visible

**Expected behavior**

100 instances of the particle effect are visible

**To Reproduce**

https://github.com/jakkos-net/bevy_hanabi_64_issue

**Screenshots**

![image](https://github.com/djeedai/bevy_hanabi/assets/45759112/e5a7796a-00bc-41a7-b9e3-4f27b65c46ab)

**Comment by djeedai** [comment]
@jakkos-net the latest change #328 fixes it for me. Let me know and feel free to reopen if there's still any issue. Thanks!
