### ISSUE TITLE
`RibbonModifier` render effects are not applied on Macs

### ISSUE THREAD

**Issue by tompuric** [djeedai/bevy_hanabi#322]
**Crate versions**
`bevy` version: 0.13.2
`bevy_hanabi` version: 0.11.0-dev

**Testing environments**

* Windows: INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 10 Pro", kernel: "19045", cpu: "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz", core_count: "4", memory: "31.9 GiB" }
* Mac: INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.4.1 ", kernel: "23.4.0", cpu: "Apple M1 Pro", core_count: "10", memory: "32.0 GiB" }

**Describe the bug**

I can't confirm if it's just me, but when running examples that utilise the `RibbonModifier` on my Mac, the effect is not applied.
All other effects work correctly. No issues on my windows machine.

**Expected behavior**

I expect to see the same behaviour as shown in the example screenshots and my windows.

**To Reproduce**

Utilise `main` branch on Mac.

**Screenshots**

Running the examples in windows

![hanabi-firework](https://github.com/djeedai/bevy_hanabi/assets/5729407/3f5124ba-e7c3-4a30-83dd-e4b208ef4458)
![hanabi-ribbon](https://github.com/djeedai/bevy_hanabi/assets/5729407/38f9432e-1fa6-41af-910b-5168d76b5a2d)
![hanabi-worms](https://github.com/djeedai/bevy_hanabi/assets/5729407/a35578fc-37a3-4137-9848-c77ca41c23ec)

Running the examples in mac

<img width="1286" alt="Screenshot 2024-05-14 at 12 44 04 AM" src="https://github.com/djeedai/bevy_hanabi/assets/5729407/cbbbc564-5d1f-4bdf-9e75-f9c3946bfe12">
<img width="1282" alt="Screenshot 2024-05-14 at 12 44 23 AM" src="https://github.com/djeedai/bevy_hanabi/assets/5729407/d51a591a-6f3a-4963-a52e-a6cf51b7d9e8">
<img width="1283" alt="Screenshot 2024-05-14 at 12 45 04 AM" src="https://github.com/djeedai/bevy_hanabi/assets/5729407/566b3d85-576f-4b0a-be9b-184f422f8df6">

**Comment by tompuric** [comment]
It seems to also impact `OrientModifier` as shown in this shot shown below for the `portal` example.

<img width="1284" alt="Screenshot 2024-05-14 at 1 20 54 AM" src="https://github.com/djeedai/bevy_hanabi/assets/5729407/30f59822-e89e-4efb-9c75-7833a72d1b2a">

It made me question whether this was all render modifiers. But when testing others such as `SetColorModifier` for instance, there was no issues.

So I began to dig into the `apply_render` fn for `RibbonModifier`. When exploring this area, it seems that `next_index` is always set to the maximum number of `4294967295`, which always returns `out`. I'm not sure where `particle.next` is set but that's where i'd explore next.

**Comment by senpaaii** [comment]
Can confirm I repeated the same steps on my M1 Mac and had the exact same results as @tompuric

**Comment by djeedai** [comment]
I have some similar repro, I will try to figure out if I can debug the GPU on macOS.

**Comment by djeedai** [comment]
Ok I know what's going on, this is a storage buffer alignment issue. Most desktop platforms require a 32-byte alignment, but Metal requires a 256-byte one, and some code ignores that and aligns to 32 bytes always.

**Comment by djeedai** [comment]
Any chance someone can try the `u/pad256` branch? @tompuric  or @senpaaii? I've fixed several bugs, although the `instancing.rs` example still exhibits a bug where some particles spawn but don't move (add with SPACE, delete with DELETE). But all the padding ones and some out of bound access in the clone modifier are fixed, and that fixes all other examples for me on macOS.

**Comment by tompuric** [comment]
Amazing, it's working ❤️ 

I've attached some low quality gifs just to showcase it working.

![hanabi_ribbon](https://github.com/djeedai/bevy_hanabi/assets/5729407/7dd14986-c13c-4072-aa72-6965ff17ddb5)
![hanabi_worms](https://github.com/djeedai/bevy_hanabi/assets/5729407/d1f5ce6f-1e2c-41f5-9f54-8df3be2186ec)
![hanabi_firework](https://github.com/djeedai/bevy_hanabi/assets/5729407/9b027c07-857a-4363-911d-52b0c0b6dd1e)
