### ISSUE TITLE
Allow seeding of `writer.rand()`

### ISSUE THREAD

**Issue by jakkos-net** [djeedai/bevy_hanabi#333]
**Describe the solution you'd like**

As far as I can tell ( maybe I'm wrong :) ) there is no way to seed the `writer.rand` function, so different instances of the same particle effect will get the same random value. 

E.g. when creating a particle ribbon effect and setting the velocity with:
```rust
SetAttributeModifier {
        attribute: Attribute::VELOCITY,
        value: ((writer.rand(ValueType::Vector(VectorType::VEC3F))
            + writer.lit(vec3(-0.5, -0.5, 0.0)))
            * writer.lit(vec3(200.0, 200.0, 0.0)))
        .expr(),
    }
```

all instances of the ribbons effect move in the same direction, see image below:
![image](https://github.com/djeedai/bevy_hanabi/assets/45759112/8c8aa862-f934-4d80-8da6-3c55d970662d)

Ideally I'd want to seed the `rand` function with combinations of position, time, particle id etc..

**Comment by djeedai** [comment]
There's a bug where the update pass compute shader is not seeded correctly. This is probably why you're seeing this. This is made worse by the fact the init compute pass (which is seeded correctly) doesn't run on cloned particles, so you have to "init" them inside the update pass, which is a limitation of the design at the minute, and as a result you can't work around the unseeded rand.

**Comment by djeedai** [comment]
I've closed since the bug on update pass is fixed. Please feel free to reopen though @jakkos-net in case there's still an issue for your use case. Thanks!
