### ISSUE TITLE
Ribbon modifier doesn't render anything

### ISSUE THREAD

**Issue by MatrixDev** [djeedai/bevy_hanabi#339]
**Crate versions**
`bevy` version: `0.13`
`bevy_hanabi` version: `0.11.0` (reproduces on `main` branch as well)

**Describe the bug**
In short nothing renders after adding `RibbonModifier`.

I might misunderstood how to use `RibbonModifier` so this might not be a bug. My sample is simpler than what you have in examples folder but I still think it should still work. BTW `move_particle_effect` system doesn't do anything in that example (I've commented it out and everything is the same).

**Expected behavior**
`RibbonModifier` should work without using clone modifier from example.

**To Reproduce**
```rust
use std::f32::consts::TAU;

use bevy::DefaultPlugins;
use bevy::math::vec4;
use bevy::prelude::*;
use bevy_hanabi::{Attribute, ColorOverLifetimeModifier, EffectAsset, ExprWriter, Gradient, HanabiPlugin, OrientMode, OrientModifier, ParticleEffect, ParticleEffectBundle, RibbonModifier, SetAttributeModifier, SimulationSpace, SizeOverLifetimeModifier, Spawner};

#[derive(Component)]
struct Source;

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, HanabiPlugin))
        .add_systems(Startup, setup)
        .add_systems(Update, update)
        .run();
}

fn setup(
    mut commands: Commands,
    mut effects: ResMut<Assets<EffectAsset>>,
) {
    let writer = ExprWriter::new();

    let init_size_attr = SetAttributeModifier {
        attribute: Attribute::SIZE,
        value: writer.lit(0.125).expr(),
    };

    let init_position_attr = SetAttributeModifier {
        attribute: Attribute::POSITION,
        value: writer.lit(Vec3::ZERO).expr(),
    };

    let init_velocity_attr = SetAttributeModifier {
        attribute: Attribute::VELOCITY,
        value: writer.lit(Vec3::ZERO).expr(),
    };

    let init_age_attr = SetAttributeModifier {
        attribute: Attribute::AGE,
        value: writer.lit(0.0).expr(),
    };

    let init_lifetime_attr = SetAttributeModifier {
        attribute: Attribute::LIFETIME,
        value: writer.lit(1.0).expr(),
    };

    let render_size = SizeOverLifetimeModifier {
        gradient: Gradient::linear(Vec2::splat(0.123), Vec2::ZERO),
        screen_space_size: false,
    };

    let render_color = ColorOverLifetimeModifier {
        gradient: Gradient::linear(vec4(3.0, 0.0, 0.0, 0.5), vec4(3.0, 0.0, 0.0, 0.0)),
    };

    let effect = EffectAsset::new(
        vec![256],
        Spawner::rate(256.0.into()),
        writer.finish(),
    )
        .with_name("ribbon")
        .with_simulation_space(SimulationSpace::Global)
        .init(init_size_attr)
        .init(init_position_attr)
        .init(init_velocity_attr)
        .init(init_age_attr)
        .init(init_lifetime_attr)
        .render(RibbonModifier)
        .render(OrientModifier::new(OrientMode::FaceCameraPosition))
        .render(render_size)
        .render(render_color);

    let effect = effects.add(effect);

    commands.spawn((
        Camera3dBundle {
            transform: Transform::from_xyz(1., 5., 1.).looking_at(Vec3::new(0.0, 0.0, 0.0), Vec3::Y),
            ..default()
        },
    ));

    commands.spawn((
        ParticleEffectBundle {
            effect: ParticleEffect::new(effect.clone()),
            transform: Transform::IDENTITY,
            ..default()
        },
        Source,
    ));
}

fn update(
    mut query: Query<&mut Transform, With<Source>>,
    time: Res<Time>,
) {
    for mut transform in query.iter_mut() {
        let angle = time.elapsed_seconds_wrapped().fract() * TAU;
        transform.translation.x = angle.cos();
        transform.translation.z = angle.sin();
    }
}
```

**Screenshots**
Everything renders without `RibbonModifier`:
<img width="541" alt="image" src="https://github.com/djeedai/bevy_hanabi/assets/1215187/42b0107b-495b-44ca-bc76-876f8a382efb">

**Comment by MatrixDev** [comment]
Forgot to add, I'm running this on my M1 laptop. I don't think it is M1 related problem because example works for me.

**Comment by djeedai** [comment]
@MatrixDev the way ribbons work is not intuitive. You have a single particle group, and no `CloneModifier`. The `RibbonModifier` works by chaining 1 "head" particle from group 0 with all associated "cloned" particles from group 1. Here you're not cloning anything so the ribbon has nothing to render (can't make a ribbon with 1 particle). And because it's present, the head particle itself doesn't render. You should look at the `ribbon.rs` example. Basically for 1 ribbon you need to spawn 1 particle in the first group (0), and then N particles making up the ribbon in group 1. Then when you move the head particle of group 0 around, each frame the other particles in group 1 will get automatically updated to the previous position of the particle before them, which will create the ribbon.

**Comment by MatrixDev** [comment]
hi @djeedai, thanks for answering. but I don't understand than how to make a particle in group 0 (tail particle) follow my entity? I can set `SimulationSpace` to `Local` but than whole ribbon will be in local space and I don't want it.

Is it possible to have group 0 in global space and group 1 in local?

`ribbon.rs` doesn't really help me because entity position there doesn't matter, only calculations in expression. should I use properties to update group 0 position each time my entity position changes?

**Comment by MatrixDev** [comment]
@djeedai, thanks a lot for your answer but... sorry, I still can't make it to work...

So I've modified `ribbon.rs` example by (following your instructions):
1. changing to local space `.with_simulation_space(SimulationSpace::Local)`
2. removing `.update_groups(move_modifier, ParticleGroupSet::single(0))` so that `head` particle only follows the entity instead of using expression.
3. added gizmo just to see where entity is actually located

Everything else is the same in the example but the ribbon is still not rendered :(
<img width="1281" alt="image" src="https://github.com/djeedai/bevy_hanabi/assets/1215187/de4f2a58-2d24-4995-9ab1-f8ed3918f986">

What I think is happening is all particles (head and ribbon) are always set to `Vec3::ZERO` position in the local space of the entity. Because of this nothing is drawing. Example modifies actual position of the head particle directly, so all cloned particles always have different position.

BTW yes, I meant "head" particle, not "tail" back there.

**Comment by djeedai** [comment]
Hum... yes of course that suggestion was stupid, the `RibbonModifier` only looks at the simulation space, and there the head particle doesn't move, so all cloned tail particles also don't move. Stupid me.

You probably need to drive the head particle with a property you setup and update manually, and use `GlobalSpaceSimulation`. The `spawn_on_command.rs` example shows how to use properties (it uses them to spawn the effect based on the collision normal that the CPU calculated).

**Comment by MatrixDev** [comment]
@djeedai, yeap, it works with properties. but... it doesn't work with `SizeOverLifetimeModifier` now.

<img width="1270" alt="image" src="https://github.com/djeedai/bevy_hanabi/assets/1215187/a19d3be7-918e-408a-a2ae-05ab1be890b1">

I've just added this modifier in the example:
```rust
    let render_size = SizeOverLifetimeModifier {
        gradient: Gradient::linear(Vec2::splat(0.5), Vec2::ZERO),
        screen_space_size: false,
    };

   // EffectAsset::new...
   .render_groups(render_size, ParticleGroupSet::single(1))
```

**Comment by djeedai** [comment]
Nobody ever tried that to be honest. I'm pretty sure it'll not work with `RibbonModifier` because they both try to change the quad size and orientation, so whichever comes last wins. But I'm surprised it doesn't work without, because the render modifier should work on any group.

**Comment by djeedai** [comment]
Oh, is that screenshot actually with the `RibbonModifier`? I thought it was without. If so then that's exactly what I described, the `SizeOverLifetimeModifier` comes last and undoes the work the `RibbonModifier` did to chain particles together. I'll have to think about how to fix that without special casing this particular couple of modifiers too much.

**Comment by MatrixDev** [comment]
@djeedai, it is original example with `SizeOverLifetimeModifier` added. Is there maybe any other way of making ribbon shrink over lifetime (like using expressions or something)?

**Comment by djeedai** [comment]
It looks like `RibbonModifier` only changes the X size of particles, so I'm guessing whatever way (modifier or expression) changing the Y size should work. But it needs to be executed before the ribbon modifier. So you can try inserting the `SizeOverLifetimeModifier` first, maybe that works already?

https://github.com/djeedai/bevy_hanabi/blob/b9a98bdf51be07f8127d2f16b68f1eb86259242f/src/modifier/ribbon.rs#L39

**Comment by djeedai** [comment]
Closing this. The latest version changed how ribbons work, and the `ribbon.rs` example now has a `SizeOverLifetimeModifier` which works as expected.
