### ISSUE TITLE
Unnecessary unwrap that can cause panic.

### ISSUE THREAD

**Issue by mintlu8** [djeedai/bevy_hanabi#343]
**Crate versions**
main (0.11.0)

**Describe the bug**
This line should be a filter instead of unwrap. This can be an instant panic if the handle is added via `AssetServer` instead of `Assets<EffectAsset>`

```rust
effects.get(&effect.asset).unwrap()
```

**Comment by djeedai** [comment]
Thanks @mintlu8 for reporting. I agree it's a bit dangerous, but not exactly as you describe. Here `effect` is a `CompiledParticleEffect`, so its `asset` field shouldn't be set directly by the user. Instead, it's updated automatically by `compile_effects()`, and that system checks that the asset is loaded. That being said, I realized that if you don't set any asset (invalid handle), then the `CompiledParticleEffect` keeps its default handle value (invalid), and indeed you can end up in that codepath. But that's unrelated to `AssetServer` I think. I'll fix anyway.
