### ISSUE TITLE
Bevy 0.8 Support

### ISSUE THREAD

**Issue by Eaven** [djeedai/bevy_hanabi#35]
Hey there

Super excited to use with bevy 0.8!

Any plans to support?

**Comment by djeedai** [comment]
Yes, I'm waiting for `bevy_inspector_egui` to be available for 0.8, which the examples depend on. The maintainer told me this should be available soon. Once it's available there will be a `0.3.0` release compatible with Bevy 0.8.

**Comment by djeedai** [comment]
Blocked on jakobhellermann/bevy-inspector-egui#75

**Comment by DidiBear** [comment]
The new version 0.12.0 of `bevy-inspector-egui` supporting `bevy` 0.8 [has just been released here](https://github.com/jakobhellermann/bevy-inspector-egui/tree/v0.12.0#bevy-support-table) 😃

**Comment by djeedai** [comment]
Yes I've started porting, although `bevy_hanabi` is heavy on rendering integration and that part changed quite a bit in Bevy 0.8 so I'll do my best but that might take a bit.

**Comment by djeedai** [comment]
Update: I think I have a working version. It has a couple of dirty hacks I'd like to remove, and I only tested 2 examples so far, but things seem to work. Hopefully if I find time this week-end we could have a new Release supporting Bevy 0.8. No promise though 😅

**Comment by djeedai** [comment]
Support added, and just published v0.3.0 with it.
