### ISSUE TITLE
Ability to sample textures in modifiers

### ISSUE THREAD

**Issue by msvbg** [djeedai/bevy_hanabi#355]
**Describe the solution you'd like**
Add the ability to sample a texture in Hanabi modifiers.

**Describe _why_ you want that solution. Is this related to a problem?**
There are a variety of ways this could be applied, like spawning particles in interesting patterns using pre-made textures (like Noita does), or crudely approximating 2D collisions on the GPU by intersecting particles with a world texture.

**Comment by djeedai** [comment]
@msvbg would you mind expanding on "like Noita does"? I'm always curious to learn about particle effect techniques, but I'm not familiar about any tech talk or presentation about Noita.

On the feature itself yes this is planned.

**Comment by msvbg** [comment]
I believe I got it from this place: https://noita.fandom.com/wiki/Modding:_Image_Emitters. Specifically, the "Image Emitters" and "Advanced Image Emitters" sections. This is how they get effects like these in the game:

https://github.com/user-attachments/assets/ef2cf55c-ad0a-4dde-aa20-f488fec6547b

**Comment by djeedai** [comment]
Added some initial support. This is fairly limited but it should be easy enough to build on it to add more features.
