### ISSUE TITLE
Trails randomly disappear

### ISSUE THREAD

**Issue by Seldom-SE** [djeedai/bevy_hanabi#403]
**Crate versions**
`bevy` version: 0.15.0
`bevy_hanabi` version: `main` (currently `d40741e`)

**Describe the bug**
After updating to Bevy 0.15 and `bevy_hanabi` `main`, trails randomly disappear

**Expected behavior**
Trails remain visible

**To Reproduce**
I haven't had time to tinker with this much, so I don't really know the specifics, sorry. The `firework` example doesn't have the issue, even when I spawn an additional instance.

**Screenshots**

https://github.com/user-attachments/assets/ac3bf746-6512-4d06-be8c-29fe474a212f

**Comment by djeedai** [comment]
Thanks @Seldom-SE, I've seen some weird things in the `instancing` example too, and I was blocking the release on that. Haven't had the time to get a smaller repro and investigate though.
