### ISSUE TITLE
WASM compatibility

### ISSUE THREAD

**Issue by ZettaScript** [djeedai/bevy_hanabi#41]
Using `bevy_hanabi` fails in WASM because `VERTEX_WRITABLE_STORAGE` is not supported (even if WGPU doc says it is supported by all platforms).

Is it planned to make this crate WASM-compatible?

**Comment by djeedai** [comment]
No, `bevy_hanabi` uses compute shaders which are not currently supported on Web.

**Comment by djeedai** [comment]
I'm going to close this issue. I fully appreciate the value of wasm, and I'm kind of sad that this crate doesn't work with it, but it would be such a large amount of work not only to create a separate backend dedicated to wasm that doesn't use compute shaders, but also to maintain two backends in parallel, that I realistically don't have the time to do this.

I hear some Bevy users are working on a CPU particle solution, which would work with wasm (see bevyengine/rfcs#28) so I encourage anyone who needs a particle system that works in wasm to contribute to that RFC and workstream.

If you're familiar with Unity, and to hazard an over-flattering comparison that is probably not realistic (yet?), 🎆 Bevy Hanabi is to Unity's VFX Graph what that CPU solution and RFC for Bevy is to Unity's built-in particle system, with the same advantages and drawbacks. CPU solutions are more versatile, easier to support on all platforms, but limited in terms of performance; on the other hand GPU solutions are vastly more performant but require modern API and hardware features (compute shaders) which are not available everywhere.

**Comment by johanhelsing** [comment]
too, bad, but I totally undestand your decision. I guess we can only hope that webgpu will solve this in the future...

maybe add a small note in the readme that wasm is not supported?

**Comment by djeedai** [comment]
> maybe add a small note in the readme that wasm is not supported?

I thought I already had but apparently not. Fixed now, it's in the README.

**Comment by janhohenheim** [comment]
AFAIK compute shaders are now supported by WebGPU. @djeedai would you consider reopening this issue?

**Comment by djeedai** [comment]
@janhohenheim I would be more than happy to add wasm support to 🎆 Hanabi provided Bevy itself supports compute shaders on wasm. I don't believe this is the case yet though? And I can really spearhead that myself.

**Comment by janhohenheim** [comment]
@djeedai hmm, I tried the `compute_shader_game_of_life` example on main and forced the wgpu backend to WebGPU by calling the following on the `DefaultPlugin` setup:
```rust
.set(RenderPlugin {
    wgpu_settings: WgpuSettings {
        backends: Some(Backends::BROWSER_WEBGPU),
        ..default()
    },
})
```
However, I cannot test this further, since I fail to activate WebGPU on my browsers. I cannot render __any__ WebGPU examples on the internet right now. Maybe someone else has better luck? The steps needed to enable WebGPU has described [here](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status)

**Comment by janhohenheim** [comment]
@johanhelsing ah heck! I checked Discord and found this:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/9047632/221229392-2de98fa1-5c51-48fc-9969-dd380fcee442.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/9047632/221229425-953a1dd8-3014-493a-b808-44fd9daeb196.png">
I deduce from this that you might get `webgpu` running if you enable the respective feature on `wgpu`. But it seems this is not yet part of any public facing Bevy API.

**Comment by djeedai** [comment]
So yes, that's my understanding, and happy to reopen this once Bevy supports it but until then no luck in afraid.

**Comment by StaffEngineer** [comment]
Seems like there is official support for WebGPU in bevy's main branch, should this issue be reopened?

**Comment by mockersf** [comment]
I ported bevy_hanabi to main, and with a few fixes for WebGPU it works in the browser

https://github.com/djeedai/bevy_hanabi/assets/8672791/fa5979ca-3008-42c0-9ae9-00752645bd9d

**Comment by StaffEngineer** [comment]
@mockersf great, do you have a branch to try? :)

**Comment by mockersf** [comment]
just pushed it here: https://github.com/mockersf/bevy_hanabi/tree/with-webgpu, started from https://github.com/djeedai/bevy_hanabi/pull/179 for some of the Bevy update needed

**Comment by djeedai** [comment]
Reopening the issue now that Bevy had official support.

**Comment by djeedai** [comment]
I did some initial work and I can build and run all examples. However there's a major bug where only the first effect is visible, and I'm having difficulties debugging on Web (notably, at the minute logs don't show up in console like they should, and I don't know of any way to make GPU captures). So this likely won't make it for the next release unfortunately (next few days, waiting on `bevy-inspector-egui` to upgrade to Bevy 0.11).

**Comment by adamtomecek** [comment]
@djeedai could you create a draft PR with that you have? So me and others can maybe help with debugging

**Comment by djeedai** [comment]
@adamtomecek See the `u/wasm` branch, I think it has my latest try.

**Comment by adamtomecek** [comment]
Unfortunately no luck running it. It panicks on me with Current version, `u/wasm` branch and mockersf WASM support branch.

```
Caused by:
    In Device::create_bind_group_layout
      note: label = `hanabi:bind_group_layout:dispatch_indirect_dispatch_indirect`
    Too many bindings of type StorageBuffers in Stage ShaderStages(COMPUTE), limit is 0, count was 3
```

**Comment by mockersf** [comment]
Are you building for WebGL2 or WebGPU?

**Comment by adamtomecek** [comment]
Good question. Not sure. I'm pretty new to Rust/Bevy but I think it's safe to say I'm using default values?

`RUSTFLAGS=--cfg=web_sys_unstable_apis cargo run --target wasm32-unknown-unknown` this is a command I'm using to run it.

**Comment by djeedai** [comment]
Can you run all examples? At the time I made the branch I could only run examples with a single effect. As soon as there were more, only the first rendered.

**Comment by adamtomecek** [comment]
...works spot on with my game, but I use multiple effects. I create all effects while loading the game, save `Handle`s and run effect when needed.

I'll give examples here a try and let you know

**Comment by djeedai** [comment]
I tested on latest, there's no change. See for example the `spawn` example, it's missing the second and third effects. I have no idea how to debug the GPU on WASM in the browser, I don't think there's any tool like RenderDoc. So it might take a while to figure out what the browser is not liking.

![image](https://github.com/djeedai/bevy_hanabi/assets/6532395/794c7416-43fe-40ec-bfe8-5a44c4d71ca8)

**Comment by adamtomecek** [comment]
@djeedai 
<img width="1286" alt="Screenshot 2023-09-04 at 16 21 55" src="https://github.com/djeedai/bevy_hanabi/assets/157048/3847c8e9-588b-4db1-9199-4223ca773d0d">

I see all three effects. I couldn't compile examples from your `u/wasm` branch, I use my custom rebased with my `Cargo.toml`. I'll make a working example and send you a link.

**Comment by djeedai** [comment]
Yes I had to remove the inspector too, but I still don't see the other effects beyond the first one.

**Comment by adamtomecek** [comment]
@djeedai [code that's working for me](https://github.com/adamtomecek/bevy_hanabi/tree/wasm). Sadly can't see any major changes compared to your version. Running it like this `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo run --example spawn --features="bevy/bevy_winit bevy/bevy_pbr 3d" --target wasm32-unknown-unknown` with added Cargo config file for a WASM runner.

**Comment by djeedai** [comment]
@adamtomecek Indeed the code looks the same. The build command too, mine is:

```sh
cargo b --release --example spawn --target wasm32-unknown-unknown --no-default-features --features="bevy/bevy_winit bevy/bevy_pbr 3d"
wasm-bindgen --out-name wasm_spawn --out-dir examples/wasm/target --target web target/wasm32-unknown-unknown/release/examples/spawn.wasm
```

From there I run `basic-http-server examples/wasm` and point Chrome at `http://127.0.0.1:4000`. I'm unclear what you're doing on your side, I don't know what "added Cargo config file for a WASM runner." means. Can you also please confirm on which platform you run? Just to see if there's a pattern here.

I noted you build in Debug, while I build in Release. However I tried in Debug and it doesn't change anything.

**Comment by adamtomecek** [comment]
@djeedai 
> I'm unclear what you're doing on your side, I don't know what "added Cargo config file for a WASM runner." means

My config. I think the result should be identical. Release and Debug makes no difference for me. Both work.
```
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
```

> Can you also please confirm on which platform you run?

I have a Macbook Air M2 with latest MacOS

**Comment by adamtomecek** [comment]
@djeedai can you see effects in this "game" I made? https://tds.tmck.cz/

**Comment by djeedai** [comment]
> @djeedai do you see effects in this "game" I made? https://tds.tmck.cz/ There should be firework like effect when you hit an enemy.

Only on the first killed enemy. Well that's kind of a partial relief, I'm not getting insane, this really looks like a platform bug. 

FYI @superdump see the above website, on Windows PC with Chrome 116 I don't see the effects after the first one, whereas @adamtomecek can see them all on a Macbook Air M2. This looks like a Chrome bug maybe?

**Comment by adamtomecek** [comment]
Had a friend running W10 and latest Chrome test it and he also sees only first one.

**Comment by mockersf** [comment]
on macOS with an m1 and chromium 117, I see them all... so yeah looks like a chrome bug

**Comment by Elabajaba** [comment]
> https://tds.tmck.cz/

Windows + chrome 117 I also only get the first effect (per enemy type).

On firefox nightly with webgpu enabled it works! It's laggy, but particles spawn every time I kill an enemy. I had to set `dom.webgpu.wgpu-backend` = `vulkan` (it was defaulting to dx12 which wasn't working) and `dom.webgpu.indirect-dispatch.enabled` = `true` in about:config for it to work.

**Comment by djeedai** [comment]
Thanks for the data point, much appreciated. Do you recall what kind of error if any you had with dx12? I'll dig into that indirect dispatch flag too, try to understand why it's not active by default.

**Comment by AlienSmith** [comment]
Good news everyone. The spawn example works fine with win10 + Chrome(124.0.6367.202) and it works on Edge too.
![image](https://github.com/user-attachments/assets/fba1409f-48ff-4fa0-956d-19144540f3a7)

**Comment by dlight** [comment]
Could the readme be updated? And maybe have official support for wasm in Hanabi.

The readme currently says typetag doesn't work on wasm, [but it does](https://github.com/dtolnay/typetag/pull/96/commits/b68beb630eba78af7bf9015283d168f4b05e0313) with extra setup
