### ISSUE TITLE
ParticleEffectBundle don't despawn

### ISSUE THREAD

**Issue by M3G4L04D0N** [djeedai/bevy_hanabi#45]
I added a ParticleEffectBundle as a child of my Player entity, however when despawn_recursive() is called, the particle don't despawn and stay there. Also the particle won't spawn a second time if the player respawns. 
Maybe I got wrong how to spawn and despawn particles bundle, didn't found any way of deleting / despawning particles in the examples.

**Comment by djeedai** [comment]
Yes I think that's a bug I need to go investigate that. Sorry about that.

**Comment by djeedai** [comment]
Confirmed that if you `despawn_recursive()` an entity with a `ParticleSystem`, the particles continue to update. Which is not exactly what you describe @M3G4L04D0N so I'm not sure why the difference.

**Comment by M3G4L04D0N** [comment]
Not sure what you meant by that, yes the particles continue to update as it continues to emit particles, and don't simply gets despawned as other children, so in my case the particles continue to exist in the game over screen and is no more attached to the player so when the user hit "retry" the particle is here, still emitting in the position where the player died last time and don't move anymore with the player's movements (the ParticleSystemBundle is spawned as a child of my player and is triggered everytime the player spawns / respawns and yet it does not create a new one for some reason. When the player dies, the "despawn_recursive() method is called on it, making all children disapear except for the particle system continuing to exist until the app exit).

**Comment by djeedai** [comment]
> the particles continue to update as it continues to emit particles

No, that's not my experience. I modified the `spawn` example to `despawn_recursive()` the entities where the `ParticleEffect`s are; after that, the existing particles continue to animate with gravity, but there's no new particle spawned. So although I'm not quite sure why the existing particles continue to be rendered without any `ParticleEffect` in the scene, there's nothing to spawn new particles for sure.

**Comment by djeedai** [comment]
Reopening, because the part where particles are rendered while the `ParticleEffect` is gone is definitely a bug, and I found the corresponding TODO in the code.
