### ISSUE TITLE
Despawning an entity with a `ParticleEffectBundle` keeps the particle system running

### ISSUE THREAD

**Issue by darthdeus** [djeedai/bevy_hanabi#61]
I'm not sure if I'm missing something obvious, but it seems that if I attach a `ParticleEffectBundle` to an entity, let it run for a while, and then `commands.entity(entity).despawn()`, the particle system just keeps emitting new particles at the last location of the entity.

**Comment by auderer** [comment]
This was fixed in #47, which is merged into `main`. We just need a new release.
