### ISSUE TITLE
Even when emitters are removed, they continue causing lag

### ISSUE THREAD

**Issue by auderer** [djeedai/bevy_hanabi#67]
When repeatedly creating and removing lots of emitters, they cause an increasing amount of FPS lag, even when none are in the world. It seems like something is not being fully cleaned up on removal.

**Comment by djeedai** [comment]
Did you try with latest after #66 fixed #60? Part of the bug was growing indefinitely the vector holding the GPU buffers.

**Comment by djeedai** [comment]
#69 also fixed a few more bugs, it's worth trying again. Or if you can let me know how to repro this?

**Comment by KnstAnt** [comment]
Hello. I started using your excellent library and ran into a few issues. I think they are related to what is discussed here, so I will write here. I used the library to create an effect around a projectile and ran into a few weird things. The effects of different shots behaved synchronously, although I created them separately. Over time, their appearance changed even for new shots. When new shots appeared, some of the effects from the old shots reappeared, although I had already removed their entities. I was able to create an application that roughly shows what I observed. https://github.com/KnstAnt/hanabi_test.git

**Comment by djeedai** [comment]
@KnstAnt please try again with 0.6.0 this should be fixed. Otherwise I'll have a look again.

**Comment by auderer** [comment]
@djeedai this appears to be fixed in 0.6.0 👍 great improvements in this version!!

**Comment by djeedai** [comment]
Ah fantastic, thanks @auderer for confirming!
