### ISSUE TITLE
Billboards/Particles with custom positions

### ISSUE THREAD

**Issue by ahmadaliadeel** [djeedai/bevy_hanabi#80]
Hi, I want to draw a start field but with given positions, i think its not possible rightnow. Any clue here?

**Comment by djeedai** [comment]
Hi- you mean with fixed star positions? If so I wouldn't recommend using a particle system it would be a waste of resources, unless you want the stars to animate somehow, like appear and disappear? In any case there's currently no simple way to do that, although you can _maybe_ fake it with an emitter with a very large radius covering the entire screen? So long as you don't expect to manually place those stars and instead are fine with them being randomly distributed.

**Comment by ahmadaliadeel** [comment]
thanks
