### ISSUE TITLE
Feature request: More velocity & acceleration modifiers

### ISSUE THREAD

**Issue by NiseVoid** [djeedai/bevy_hanabi#97]
Currently we can spawn particles with a radial velocity and give them acceleration in an arbitrary direction. However, for some graphical effects, especially 3D ones, these options are not enough.

I suggest adding:
- Arbitrary initial velocity (for which there seems to be a stale PR draft)
- Tangential velocity, which gives a spin in the specified axis around the origin
- Radial acceleration, similar to the current spawning behavior but as acceleration (it might be possible to abuse force field modifiers for this, but I'm not sure if that is the desired solution)
- Tangential acceleration, same as the velocity but as acceleration
- Damping, reduces the speed of particles at the specified rate. Different from negative acceleration in that it can fully stop particles.

The user should be able to combine any of these on the same effect.

Sadly, since I'm not great at 3D space math, I can't add these myself. However I can provide you some example effects that would use these modifiers:
**Flame pillar**: You spawn particles on the surface of a circle facing Y. Then combine Y+ velocity with tangential velocity.
**Whirlwind**: You spawn partciles at the surface of a circle facing Y. Then combine negative radial velocity with tangential acceleration.
**Gathering ball**: You spawn particles on the surface of a sphere. Then combine negative radial velocity with the right amount of damping so they stop near the center of the sphere
**Explosion+implosion**: You spawn particles in just about any shape. Then combine positive radial velocity with negative radial acceleration.

**Comment by djeedai** [comment]
Thanks for this! I agree with the general idea of making things more customizable, and I was thinking the same thing looking at your other GitHub items.

One thing on the acceleration: I think it's fairly unusual to have a per-particle acceleration, since acceleration represents external effects, which are almost always acting on more than 1 particle at once. However per-particle velocity yes, agreed, and the spawning velocity should be customizable independently of the position.

**Comment by djeedai** [comment]
Thanks a lot for the effect examples though, this helps me a lot think about what's missing. Much appreciated 👍

**Comment by vultix** [comment]
@djeedai On the acceleration, one use case I've had is for flames shooting out of a rocket engine.  The particles initially velocity out of the rocket is very fast, but they decelerate over time

**Comment by djeedai** [comment]
@NiseVoid I think all items are now fixed, but let me know if I've missed something.
